local q=0;local kP7O5=0;local lqT=0.0;local mP3mlD=""local PrPyxMK=0.8;local tczrIB=0.7;local a=5;local wqU76o=60
buttonWidth=wqU76o- (a*2)buttonHeight=20
overlay=CreateFrame("frame","Overlay",UIParent)overlay:SetPoint("TOP",UIParent,"TOP",300,0)
overlay:SetMovable(true)overlay:SetUserPlaced(true)
overlay:EnableMouse(true)overlay:RegisterForDrag("LeftButton")
overlay:SetScript("OnDragStart",overlay.StartMoving)
overlay:SetScript("OnDragStop",overlay.StopMovingOrSizing)overlay:SetSize(255,30)
overlay:SetFrameStrata("TOOLTIP")overlay.t=overlay:CreateTexture()
overlay.t:SetColorTexture(1,1,1,0.2)overlay.t:SetAllPoints(overlay)
button1=CreateFrame("Button",nil,overlay)button2=CreateFrame("Button",nil,overlay)
button3=CreateFrame("Button",nil,overlay)button4=CreateFrame("Button",nil,overlay)
button5=CreateFrame("Button",nil,overlay)
button1:SetPoint("TOPLEFT",overlay,"TOPLEFT",a,-a)button1:SetWidth(buttonWidth)
button1:SetHeight(buttonHeight)button1:SetText("ON")font1=CreateFont("one")
font1:SetFont("Fonts\\FRIZQT__.TTF",12)font1:SetTextColor(1,1,1)
button1:SetNormalFontObject(font1)button1:SetHighlightFontObject(font1)
button1:SetFrameStrata("TOOLTIP")local LB1Z=button1:CreateTexture()
local N9L=button1:CreateTexture()local hDc_M=button1:CreateTexture()
LB1Z:SetColorTexture(PrPyxMK,0,0,alphaColor)LB1Z:SetAllPoints()
button1:SetNormalTexture(LB1Z)N9L:SetColorTexture(0,0,0,0.5)N9L:SetAllPoints()
button1:SetHighlightTexture(N9L)hDc_M:SetColorTexture(0,0,0,0.5)
hDc_M:SetAllPoints()button1:SetPushedTexture(hDc_M)
button1:RegisterForClicks("AnyUp")
function startStop()
if q==1 then LB1Z:SetColorTexture(PrPyxMK,0,0,alphaColor)
q=0 else LB1Z:SetColorTexture(0,tczrIB,0,alphaColor)q=1 end
startStopFrame.t:SetColorTexture(q,kP7O5,lqT,alphaColor)
startStopFrame.t:SetAllPoints(startStopFrame)end;button1:SetScript("OnClick",startStop)
button2:SetPoint("TOPLEFT",overlay,"TOPLEFT",
a*2+buttonWidth,-a)button2:SetWidth(buttonWidth)
button2:SetHeight(buttonHeight)button2:SetText("CDs")font2=CreateFont("two")
font2:SetFont("Fonts\\FRIZQT__.TTF",12)font2:SetTextColor(1,1,1)
button2:SetNormalFontObject(font2)button2:SetHighlightFontObject(font2)
button2:SetFrameStrata("TOOLTIP")local qW0lRiD1=button2:CreateTexture()
local iD1IUx=button2:CreateTexture()local JLCOx_ak=button2:CreateTexture()
qW0lRiD1:SetColorTexture(PrPyxMK,0,0,alphaColor)qW0lRiD1:SetAllPoints()
button2:SetNormalTexture(qW0lRiD1)iD1IUx:SetColorTexture(0,0,0,0.5)
iD1IUx:SetAllPoints()button2:SetHighlightTexture(iD1IUx)
JLCOx_ak:SetColorTexture(0,0,0,0.5)JLCOx_ak:SetAllPoints()
button2:SetPushedTexture(JLCOx_ak)button2:RegisterForClicks("AnyUp")
function cooldownOnOff()if kP7O5 ==1 then
qW0lRiD1:SetColorTexture(PrPyxMK,0,0,alphaColor)kP7O5=0 else
qW0lRiD1:SetColorTexture(0,tczrIB,0,alphaColor)kP7O5=1 end
startStopFrame.t:SetColorTexture(q,kP7O5,lqT,alphaColor)
startStopFrame.t:SetAllPoints(startStopFrame)end;button2:SetScript("OnClick",cooldownOnOff)
button3:SetPoint("TOPLEFT",overlay,"TOPLEFT",
a*3+buttonWidth*2,-a)button3:SetWidth(80)
button3:SetHeight(buttonHeight)font3=CreateFont("three")
font3:SetFont("Fonts\\FRIZQT__.TTF",12)font3:SetTextColor(1,1,1)
button3:SetNormalFontObject(font3)button3:SetHighlightFontObject(font3)
button3:SetDisabledFontObject(font3)button3:SetFrameStrata("TOOLTIP")
normalTexture3=button3:CreateTexture()highlightTexture3=button3:CreateTexture()
pushedTexture3=button3:CreateTexture()disabledTexture3=button3:CreateTexture()
disabledTexture3:SetColorTexture(0.1,0.6,0.1,alphaColor)disabledTexture3:SetAllPoints()
button3:SetDisabledTexture(disabledTexture3)
normalTexture3:SetColorTexture(PrPyxMK,0,0,alphaColor)normalTexture3:SetAllPoints()
button3:SetNormalTexture(normalTexture3)highlightTexture3:SetColorTexture(0,0,0,0.5)
highlightTexture3:SetAllPoints()button3:SetHighlightTexture(highlightTexture3)
pushedTexture3:SetColorTexture(0,0,0,0.5)pushedTexture3:SetAllPoints()
button3:SetPushedTexture(pushedTexture3)button3:RegisterForClicks("AnyUp")
function aoeOnOff()
if lqT==0.5 then
normalTexture3:SetColorTexture(PrPyxMK,0,0,alphaColor)lqT=0 else
normalTexture3:SetColorTexture(0,tczrIB,0,alphaColor)lqT=0.5 end
startStopFrame.t:SetColorTexture(q,kP7O5,lqT,alphaColor)
startStopFrame.t:SetAllPoints(startStopFrame)end;button3:SetScript("OnClick",aoeOnOff)button5:SetPoint("TOPLEFT",overlay,"TOPLEFT",200,
-a)
button5:SetWidth(buttonWidth)button5:SetHeight(buttonHeight)
button5:SetText("Keys")font5=CreateFont("five")
font5:SetFont("Fonts\\FRIZQT__.TTF",12)font5:SetTextColor(1,1,1)
button5:SetNormalFontObject(font5)button5:SetHighlightFontObject(font5)
button5:SetFrameStrata("TOOLTIP")local hPQ=button5:CreateTexture()
local R1FIoQI=button5:CreateTexture()local NsoTwDs=button5:CreateTexture()
hPQ:SetColorTexture(PrPyxMK,0,0,alphaColor)hPQ:SetAllPoints()button5:SetNormalTexture(hPQ)
R1FIoQI:SetColorTexture(0,0,0,0.5)R1FIoQI:SetAllPoints()
button5:SetHighlightTexture(R1FIoQI)NsoTwDs:SetColorTexture(0,0,0,0.5)
NsoTwDs:SetAllPoints()button5:SetPushedTexture(NsoTwDs)
button5:RegisterForClicks("AnyUp")
function printKeybinds()printKeybinds=1;RefreshKeyBinds()end;button5:SetScript("OnClick",printKeybinds)